// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    'use strict';
    return function(match) {
      match('Tournaments/teams', 'teams#index');
      return match('Tournaments/teams/:id', 'teams#edit');
    };
  });

}).call(this);
