// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['chaplin', 'teams/models/team'], function(Chaplin, Team) {
    'use strict';

    var Teams;
    return Teams = (function(_super) {

      __extends(Teams, _super);

      function Teams() {
        return Teams.__super__.constructor.apply(this, arguments);
      }

      Teams.prototype.model = Team;

      Teams.prototype.initialize = function() {
        Teams.__super__.initialize.apply(this, arguments);
        return this.fetch();
      };

      Teams.prototype.url = '/Tournaments/api/teams';

      return Teams;

    })(Chaplin.Collection);
  });

}).call(this);
