// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['chaplin'], function(Chaplin) {
    'use strict';

    var Team;
    return Team = (function(_super) {

      __extends(Team, _super);

      function Team() {
        return Team.__super__.constructor.apply(this, arguments);
      }

      Team.prototype.idAttribute = 'Id';

      return Team;

    })(Chaplin.Model);
  });

}).call(this);
