// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'chaplin'], function(_, Chaplin) {
    'use strict';

    var TeamViewBase;
    return TeamViewBase = (function(_super) {

      __extends(TeamViewBase, _super);

      function TeamViewBase() {
        return TeamViewBase.__super__.constructor.apply(this, arguments);
      }

      TeamViewBase.prototype.getTemplateFunction = function() {
        var template, templateFunc;
        template = this.template;
        if (typeof template === 'string') {
          templateFunc = _.template(template);
          this.constructor.prototype.template = templateFunc;
        } else {
          templateFunc = template;
        }
        return templateFunc;
      };

      return TeamViewBase;

    })(Chaplin.View);
  });

}).call(this);
